# Matrices

## Numpy vs PyTorch

In [3]:
import numpy as np

In [3]:
arr = [[6,7],[8,9]]
print(arr)

[[6, 7], [8, 9]]


In [4]:
np.array(arr)

array([[6, 7],
       [8, 9]])

In [11]:
import torch

In [6]:
torch.Tensor(arr)

tensor([[6., 7.],
        [8., 9.]])

## Matrices with default values

In [10]:
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [11]:
torch.ones((3,3,3))

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [12]:
np.random.rand(2,2,2)

array([[[0.84129747, 0.13072334],
        [0.1556393 , 0.58208203]],

       [[0.41521694, 0.86355846],
        [0.19778784, 0.07110882]]])

In [13]:
torch.rand(2,2,2)

tensor([[[0.5775, 0.3702],
         [0.7191, 0.5255]],

        [[0.8579, 0.8087],
         [0.7246, 0.2262]]])

## Random values with seed

Seed is used to generate identical sets of random values

In [5]:
np.random.seed(5)
np.random.rand(2,2,2)

array([[[0.22199317, 0.87073231],
        [0.20671916, 0.91861091]],

       [[0.48841119, 0.61174386],
        [0.76590786, 0.51841799]]])

In [6]:
np.random.seed(5)
np.random.rand(2,2,2)

array([[[0.22199317, 0.87073231],
        [0.20671916, 0.91861091]],

       [[0.48841119, 0.61174386],
        [0.76590786, 0.51841799]]])

In [9]:
np.random.rand(2,2,2)

array([[[0.96366276, 0.38344152],
        [0.79172504, 0.52889492]],

       [[0.56804456, 0.92559664],
        [0.07103606, 0.0871293 ]]])

In [10]:
np.random.rand(2,2,2)

array([[[0.0202184 , 0.83261985],
        [0.77815675, 0.87001215]],

       [[0.97861834, 0.79915856],
        [0.46147936, 0.78052918]]])

In [13]:
torch.manual_seed(0)
torch.rand(2,2,2)

tensor([[[0.4963, 0.7682],
         [0.0885, 0.1320]],

        [[0.3074, 0.6341],
         [0.4901, 0.8964]]])

In [14]:
torch.manual_seed(0)
torch.rand(2,2,2)

tensor([[[0.4963, 0.7682],
         [0.0885, 0.1320]],

        [[0.3074, 0.6341],
         [0.4901, 0.8964]]])

In [15]:
torch.rand(2,2,2)

tensor([[[0.4556, 0.6323],
         [0.3489, 0.4017]],

        [[0.0223, 0.1689],
         [0.2939, 0.5185]]])

In [16]:
torch.rand(2,2,2)

tensor([[[0.6977, 0.8000],
         [0.1610, 0.2823]],

        [[0.6816, 0.9152],
         [0.3971, 0.8742]]])