# Variables and gradients

## Torch variables 

Torch variables wrap tensors and allow accumulation of gradients  

In [2]:
import torch
from torch.autograd import Variable

In [5]:
a = Variable(torch.ones(2,2,2), requires_grad = True)
print(a)

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]], requires_grad=True)


b = Variable(torch.ones(2,2,2), requires_grad = True)
print(torch.add(a,b))
print(torch.sub(a,b))
print(torch.mul(a,b))
print(torch.div(a,b))

## Torch gradients

requires_grad=True allows calculation of gradients w.r.t. the variables

In [18]:
x = Variable(torch.ones(3), requires_grad = True)
x

tensor([1., 1., 1.], requires_grad=True)

In [19]:
y = 10 * (3 * x + 3) **5
y

tensor([77760., 77760., 77760.], grad_fn=<MulBackward0>)

In [21]:
mean = (1/3) * torch.sum(y) 
mean

tensor(77760., grad_fn=<MulBackward0>)

In [22]:
mean.backward()

In [23]:
x.grad

tensor([64800.0078, 64800.0078, 64800.0078])