# Variables and gradients

## Torch variables 

Torch variables wrap tensors and allow accumulation of gradients  

In [2]:
import torch
from torch.autograd import Variable

In [5]:
a = Variable(torch.ones(2,2,2), requires_grad = True)
print(a)

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]], requires_grad=True)


In [10]:
b = Variable(torch.ones(2,2,2), requires_grad = True)
print(torch.add(a,b))
print(torch.sub(a,b))
print(torch.mul(a,b))
print(torch.div(a,b))

tensor([[[2., 2.],
         [2., 2.]],

        [[2., 2.],
         [2., 2.]]], grad_fn=<AddBackward0>)
tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]], grad_fn=<SubBackward0>)
tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]], grad_fn=<MulBackward0>)
tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]], grad_fn=<DivBackward0>)
